### PR TITLE
Redshift: Use QUALIFY statement instead of prep-CTEs to enhance performance

### LINKED ISSUE #298: [BUG] Redshift not using QUALIFY for latest records
**Describe the bug**

All macros that need to get the latest existing records should use QUALIFY instead of an additional CTE with ROW_NUMBER() and WHERE. This massively boosts performance. 

**Environment**

- Database/Platform: Redshift

### PR DESCRIPTION
**Pull request by tkiehn**
# Description

All macros that need to get the latest existing records now use QUALIFY instead of an additional CTE with ROW_NUMBER() and WHERE. This massively boosts performance.

Fixes #298 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my code

### CODE REVIEW

File: macros/tables/redshift/ma_sat_v0.sql [hunk 1]
```diff
@@ -41,44 +41,29 @@ source_data AS (
...
-
 latest_entries_in_sat AS (
 
     SELECT
         {{ parent_hashkey }},
         {{ ns.hdiff_alias }}
     FROM 
-        latest_entries_in_sat_prep
-    WHERE rn = 1  
+        {{ this }} redshift_requires_an_alias_if_the_qualify_is_directly_after_the_from
```
Comment (tkirschke) [inline macros/tables/redshift/ma_sat_v0.sql:50]: aaaaha

**Review by tkirschke — APPROVED** [review]
